#!/bin/bash

# Test script for production-like authentication with Inngest
# This tests the full signing key flow locally including:
# - Signature verification
# - In-band sync
# - Authorization header with hashed signing key

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Inngest Production Auth Test${NC}"
echo -e "${BLUE}========================================${NC}"

# Generate or use existing signing key
SIGNING_KEY_RAW=$(openssl rand -hex 32)
SIGNING_KEY="signkey-test-${SIGNING_KEY_RAW}"
EVENT_KEY="test-event-key-$(date +%s)"

echo -e "\n${GREEN}Generated test credentials:${NC}"
echo -e "  Signing Key: ${YELLOW}${SIGNING_KEY}${NC}"
echo -e "  Event Key:   ${YELLOW}${EVENT_KEY}${NC}"

# Check if inngest CLI is available
if ! command -v npx &> /dev/null; then
    echo -e "${RED}Error: npx not found. Please install Node.js${NC}"
    exit 1
fi

# Create env file for the .NET app
ENV_FILE="$PROJECT_DIR/.env.test"
cat > "$ENV_FILE" << EOF
# Generated by test-production-auth.sh
# Source this file to run the .NET app with production-like auth

export INNGEST_SIGNING_KEY="$SIGNING_KEY"
export INNGEST_EVENT_KEY="$EVENT_KEY"
export INNGEST_DEV="false"
export INNGEST_API_BASE_URL="http://127.0.0.1:8288"
export INNGEST_EVENT_API_BASE_URL="http://127.0.0.1:8288"
EOF

echo -e "\n${GREEN}Environment file created: ${ENV_FILE}${NC}"
echo -e ""
echo -e "${BLUE}┌─────────────────────────────────────────────────────────────┐${NC}"
echo -e "${BLUE}│ In another terminal, run:                                   │${NC}"
echo -e "${BLUE}│                                                             │${NC}"
echo -e "${BLUE}│   cd $PROJECT_DIR${NC}"
echo -e "${BLUE}│   source .env.test${NC}"
echo -e "${BLUE}│   dotnet run --project InngestExample${NC}"
echo -e "${BLUE}│                                                             │${NC}"
echo -e "${BLUE}│ Then open: http://localhost:8288                            │${NC}"
echo -e "${BLUE}└─────────────────────────────────────────────────────────────┘${NC}"
echo -e ""
echo -e "${GREEN}Starting Inngest Dev Server with authentication...${NC}"
echo -e "${YELLOW}Press Ctrl+C to stop${NC}\n"

# Start Inngest server with auth (use 'start' not 'dev' for signing key support)
npx inngest-cli@latest start \
    --signing-key "$SIGNING_KEY_RAW" \
    --event-key "$EVENT_KEY" \
    --port 8288
